# Generated by Django 4.2.11 on 2026-07-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_sample_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, default='General', max_length=80, verbose_name='Categoría'),
        ),
    ]
